import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font or use system fonts
// For a Nordic look, we prefer clean sans-serif

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2pt solid #3b82f6',
    paddingBottom: 10,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 5,
  },
  title: {
    fontSize: 14,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  contact: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 10,
    fontSize: 10,
    color: '#475569',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3b82f6',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  item: {
    marginBottom: 10,
  },
  itemTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  itemSubtitle: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
  },
  itemDescription: {
    fontSize: 10,
    color: '#334155',
    lineHeight: 1.4,
  },
  tailoringBadge: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f8fafc',
    border: '1pt solid #e2e8f0',
    borderRadius: 4,
  },
  tailoringText: {
    fontSize: 8,
    color: '#64748b',
    fontStyle: 'italic',
  }
});

interface CVProps {
  name: string;
  title: string;
  content: string; // Tailored content
  jobTitle?: string;
}

export const CVTemplate = ({ name, title, content, jobTitle }: CVProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.name}>{name}</Text>
        <Text style={styles.title}>{title}</Text>
        <View style={styles.contact}>
          <Text>Stockholm, SE</Text>
          <Text>contact@example.com</Text>
          <Text>portfolio.com</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Summary</Text>
        <Text style={styles.itemDescription}>
          Dedicated Graphic Designer with over 5 years of experience in the Scandinavian market. 
          Expert in minimalist aesthetic and brand identity.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Tailored Experience</Text>
        <View style={styles.item}>
          <Text style={styles.itemTitle}>{jobTitle ? `Applying for: ${jobTitle}` : 'Professional Experience'}</Text>
          <Text style={styles.itemDescription}>{content}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Skills</Text>
        <Text style={styles.itemDescription}>Figma, Adobe Creative Suite, Brand Design, UI/UX, Typography, Motion Graphics</Text>
      </View>

      <View style={styles.tailoringBadge}>
        <Text style={styles.tailoringText}>Generated by Resvio | Tailored for the European market.</Text>
      </View>
    </Page>
  </Document>
);
